import { ProficiencyLevel } from '../types';

export interface FlashcardItem {
  id: string;
  german: string;
  english: string;
  pronunciation: string;
  hint: string;
  exampleGerman: string;
  exampleEnglish: string;
  type: 'word' | 'sentence';
  level: ProficiencyLevel;
  category: 'work' | 'personal' | 'family' | 'education' | 'shopping' | 'small_talk';
  gender?: 'der' | 'die' | 'das'; // Optional gender for nouns (for Article Practice)
  nounWithoutArticle?: string;     // The raw noun without the article prefix (e.g. "Schlüssel" for "der Schlüssel")
}

export const FLASHCARD_ITEMS: FlashcardItem[] = [
  // A1 WORDS
  {
    id: 'a1-w-1',
    german: 'der Schlüssel',
    english: 'the key',
    pronunciation: '[ˈʃlʏsl̩]',
    hint: 'Used to lock and unlock doors.',
    exampleGerman: 'Wo ist mein Schlüssel für die Wohnung?',
    exampleEnglish: 'Where is my key for the apartment?',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'personal',
    gender: 'der',
    nounWithoutArticle: 'Schlüssel'
  },
  {
    id: 'a1-w-2',
    german: 'das Frühstück',
    english: 'the breakfast',
    pronunciation: '[ˈfʁyːʃtʏk]',
    hint: 'The first meal of the day.',
    exampleGerman: 'Ich esse Brot und Ei zum Frühstück.',
    exampleEnglish: 'I eat bread and egg for breakfast.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'personal',
    gender: 'das',
    nounWithoutArticle: 'Frühstück'
  },
  {
    id: 'a1-w-3',
    german: 'die Fahrkarte',
    english: 'the ticket (bus/train)',
    pronunciation: '[ˈfaːɐ̯ˌkaʁtə]',
    hint: 'You buy this to travel legally on public transit.',
    exampleGerman: 'Bitte zeigen Sie Ihre Fahrkarte.',
    exampleEnglish: 'Please show your ticket.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'shopping',
    gender: 'die',
    nounWithoutArticle: 'Fahrkarte'
  },
  {
    id: 'a1-w-4',
    german: 'entschuldigen',
    english: 'to excuse / apologize',
    pronunciation: '[ɛntˈʃʊldɪɡn̩]',
    hint: 'Verb used to say sorry or grab attention.',
    exampleGerman: 'Bitte entschuldigen Sie die Verspätung.',
    exampleEnglish: 'Please excuse the delay.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'small_talk'
  },
  {
    id: 'a1-w-5',
    german: 'bestellen',
    english: 'to order',
    pronunciation: '[bəˈʃtɛlən]',
    hint: 'To request food or goods.',
    exampleGerman: 'Ich möchte eine Pizza bestellen.',
    exampleEnglish: 'I would like to order a pizza.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'shopping'
  },
  {
    id: 'a1-w-6',
    german: 'die Wohnung',
    english: 'the apartment / flat',
    pronunciation: '[ˈvoːnʊŋ]',
    hint: 'The place where one lives.',
    exampleGerman: 'Unsere Wohnung hat drei Zimmer.',
    exampleEnglish: 'Our apartment has three rooms.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'personal',
    gender: 'die',
    nounWithoutArticle: 'Wohnung'
  },
  {
    id: 'a1-w-7',
    german: 'kosten',
    english: 'to cost',
    pronunciation: '[ˈkɔstn̩]',
    hint: 'Relates to price or value.',
    exampleGerman: 'Wie viel kostet dieses Buch?',
    exampleEnglish: 'How much does this book cost?',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'shopping'
  },
  {
    id: 'a1-w-8',
    german: 'schlafen',
    english: 'to sleep',
    pronunciation: '[ˈʃlaːfn̩]',
    hint: 'Resting overnight.',
    exampleGerman: 'Das Baby schläft schon seit zwei Stunden.',
    exampleEnglish: 'The baby has been sleeping for two hours.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'personal'
  },
  {
    id: 'a1-w-9',
    german: 'der Bahnhof',
    english: 'the train station',
    pronunciation: '[ˈbaːnˌhoːf]',
    hint: 'Where trains arrive and depart.',
    exampleGerman: 'Ich treffe dich am Bahnhof.',
    exampleEnglish: 'I am meeting you at the train station.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'personal',
    gender: 'der',
    nounWithoutArticle: 'Bahnhof'
  },
  {
    id: 'a1-w-10',
    german: 'trinken',
    english: 'to drink',
    pronunciation: '[ˈtʁɪŋkn̩]',
    hint: 'Consuming liquids.',
    exampleGerman: 'Möchtest du Wasser oder Saft trinken?',
    exampleEnglish: 'Would you like to drink water or juice?',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'personal'
  },
  {
    id: 'a1-w-11',
    german: 'der Vater',
    english: 'the father',
    pronunciation: '[ˈfaːtɐ]',
    hint: 'A male parent.',
    exampleGerman: 'Mein Vater arbeitet in Berlin.',
    exampleEnglish: 'My father works in Berlin.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'family',
    gender: 'der',
    nounWithoutArticle: 'Vater'
  },
  {
    id: 'a1-w-12',
    german: 'die Mutter',
    english: 'the mother',
    pronunciation: '[ˈmʊtɐ]',
    hint: 'A female parent.',
    exampleGerman: 'Meine Mutter kocht sehr gut.',
    exampleEnglish: 'My mother cooks very well.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'family',
    gender: 'die',
    nounWithoutArticle: 'Mutter'
  },
  {
    id: 'a1-w-13',
    german: 'das Kind',
    english: 'the child',
    pronunciation: '[kɪnt]',
    hint: 'A young human being.',
    exampleGerman: 'Das Kind spielt im Garten.',
    exampleEnglish: 'The child is playing in the garden.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'family',
    gender: 'das',
    nounWithoutArticle: 'Kind'
  },
  {
    id: 'a1-w-14',
    german: 'die Schule',
    english: 'the school',
    pronunciation: '[ˈʃuːlə]',
    hint: 'An institution for educating children.',
    exampleGerman: 'Meine Kinder gehen zur Schule.',
    exampleEnglish: 'My children go to school.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'education',
    gender: 'die',
    nounWithoutArticle: 'Schule'
  },
  {
    id: 'a1-w-15',
    german: 'der Lehrer',
    english: 'the teacher',
    pronunciation: '[ˈleːʁɐ]',
    hint: 'A person who teaches.',
    exampleGerman: 'Der Lehrer erklärt die Grammatik.',
    exampleEnglish: 'The teacher explains the grammar.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'education',
    gender: 'der',
    nounWithoutArticle: 'Lehrer'
  },
  {
    id: 'a1-w-16',
    german: 'das Buch',
    english: 'the book',
    pronunciation: '[buːx]',
    hint: 'Written or printed work consisting of pages.',
    exampleGerman: 'Ich lese ein deutsches Buch.',
    exampleEnglish: 'I am reading a German book.',
    type: 'word',
    level: ProficiencyLevel.A1,
    category: 'education',
    gender: 'das',
    nounWithoutArticle: 'Buch'
  },

  // A1 SENTENCES
  {
    id: 'a1-s-1',
    german: 'Wie geht es Ihnen?',
    english: 'How are you? (Formal)',
    pronunciation: '[viː ɡeːt ɛs ˈiːnən]',
    hint: 'A polite, formal greeting for business or strangers.',
    exampleGerman: 'Guten Tag, Herr Schmidt! Wie geht es Ihnen?',
    exampleEnglish: 'Good day, Mr. Schmidt! How are you?',
    type: 'sentence',
    level: ProficiencyLevel.A1,
    category: 'small_talk'
  },
  {
    id: 'a1-s-2',
    german: 'Ich möchte bitte einen Kaffee bestellen.',
    english: 'I would like to order a coffee, please.',
    pronunciation: '[ɪç ˈmœçtə ˈbɪtə ˈaɪ̯nən ˈkafe bəˈʃtɛlən]',
    hint: 'Common phrase used in cafés.',
    exampleGerman: 'Ich möchte bitte einen Kaffee bestellen, schwarz.',
    exampleEnglish: 'I would like to order a coffee, black please.',
    type: 'sentence',
    level: ProficiencyLevel.A1,
    category: 'shopping'
  },
  {
    id: 'a1-s-3',
    german: 'Entschuldigung, wo ist der Bahnhof?',
    english: 'Excuse me, where is the train station?',
    pronunciation: '[ɛntˈʃʊldɪɡʊŋ voː ɪst deːɐ̯ ˈbaːnˌhoːf]',
    hint: 'Asking directions politely.',
    exampleGerman: 'Entschuldigung, wo ist der Bahnhof? Ich bin verloren.',
    exampleEnglish: 'Excuse me, where is the train station? I am lost.',
    type: 'sentence',
    level: ProficiencyLevel.A1,
    category: 'small_talk'
  },
  {
    id: 'a1-s-4',
    german: 'Das macht zusammen fünfzehn Euro.',
    english: 'That comes to fifteen euros in total.',
    pronunciation: '[das maxt tsuˈzamən ˈfʏnftseːn ˈoɪ̯ʁo]',
    hint: 'Telling someone the total price to pay.',
    exampleGerman: 'Das macht zusammen fünfzehn Euro, bitte.',
    exampleEnglish: 'That comes to fifteen euros in total, please.',
    type: 'sentence',
    level: ProficiencyLevel.A1,
    category: 'shopping'
  },
  {
    id: 'a1-s-5',
    german: 'Ich lerne jeden Tag Deutsch.',
    english: 'I learn German every day.',
    pronunciation: '[ɪç ˈlɛʁnə ˈjeːdn̩ taːk dɔʏ̯tʃ]',
    hint: 'An expression of daily study habits.',
    exampleGerman: 'Ich lerne jeden Tag Deutsch mit dieser App!',
    exampleEnglish: 'I learn German every day with this app!',
    type: 'sentence',
    level: ProficiencyLevel.A1,
    category: 'education'
  },
  {
    id: 'a1-s-6',
    german: 'Es freut mich, Sie kennenzulernen.',
    english: 'It is a pleasure to meet you. (Formal)',
    pronunciation: '[ɛs fʁɔʏ̯t mɪç ziː ˈkɛnəntsuˌlɛʁnən]',
    hint: 'Say this to express happiness upon meeting someone formally.',
    exampleGerman: 'Hallo Frau Müller! Es freut mich, Sie kennenzulernen.',
    exampleEnglish: 'Hello Mrs. Müller! It is a pleasure to meet you.',
    type: 'sentence',
    level: ProficiencyLevel.A1,
    category: 'small_talk'
  },
  {
    id: 'a1-s-7',
    german: 'Ich liebe meine Familie.',
    english: 'I love my family.',
    pronunciation: '[ɪç ˈliːbə ˈmaɪ̯nə faˈmiːli̯ə]',
    hint: 'Expressing love for relatives.',
    exampleGerman: 'Ich liebe meine Familie über alles.',
    exampleEnglish: 'I love my family more than anything.',
    type: 'sentence',
    level: ProficiencyLevel.A1,
    category: 'family'
  },

  // A2 WORDS
  {
    id: 'a2-w-1',
    german: 'die Bewerbung',
    english: 'the job application',
    pronunciation: '[bəˈvɛʁbʊŋ]',
    hint: 'Document submitted to seek employment.',
    exampleGerman: 'Ich muss eine Bewerbung schreiben.',
    exampleEnglish: 'I have to write a job application.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'work',
    gender: 'die',
    nounWithoutArticle: 'Bewerbung'
  },
  {
    id: 'a2-w-2',
    german: 'der Umzug',
    english: 'the move (house/location)',
    pronunciation: '[ˈʊmˌtsuːk]',
    hint: 'Moving from one apartment or place to another.',
    exampleGerman: 'Der Umzug am Samstag war sehr anstrengend.',
    exampleEnglish: 'The move on Saturday was very exhausting.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'personal',
    gender: 'der',
    nounWithoutArticle: 'Umzug'
  },
  {
    id: 'a2-w-3',
    german: 'die Gesundheit',
    english: 'the health / wellness',
    pronunciation: '[ɡəˈzʊnthaɪ̯t]',
    hint: 'Condition of the body or mind; also said when someone sneezes.',
    exampleGerman: 'Essen Sie mehr Obst für Ihre Gesundheit.',
    exampleEnglish: 'Eat more fruit for your health.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'personal',
    gender: 'die',
    nounWithoutArticle: 'Gesundheit'
  },
  {
    id: 'a2-w-4',
    german: 'empfehlen',
    english: 'to recommend',
    pronunciation: '[ɛmˈpfeːlən]',
    hint: 'To advise or suggest something as beneficial.',
    exampleGerman: 'Können Sie mir ein schönes Hotel empfehlen?',
    exampleEnglish: 'Can you recommend a nice hotel to me?',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'small_talk'
  },
  {
    id: 'a2-w-5',
    german: 'verzichten',
    english: 'to do without / yield / abstain',
    pronunciation: '[fɛɐ̯ˈtsɪçtn̩]',
    hint: 'Requires preposition "auf". Giving up a claim or item.',
    exampleGerman: 'Ich möchte auf Zucker im Kaffee verzichten.',
    exampleEnglish: 'I want to do without sugar in my coffee.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'personal'
  },
  {
    id: 'a2-w-6',
    german: 'die Unterkunft',
    english: 'the accommodation / lodging',
    pronunciation: '[ˈʊntɐˌkʊnft]',
    hint: 'A place to stay overnight (e.g. hotel, hostel, flat).',
    exampleGerman: 'Haben wir schon eine Unterkunft für den Urlaub?',
    exampleEnglish: 'Do we already have an accommodation for the holiday?',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'personal',
    gender: 'die',
    nounWithoutArticle: 'Unterkunft'
  },
  {
    id: 'a2-w-7',
    german: 'überweisen',
    english: 'to transfer (funds/money)',
    pronunciation: '[ˌyːbɐˈvaɪ̯zn̩]',
    hint: 'To send money electronically to another bank account.',
    exampleGerman: 'Ich muss die Miete bis morgen überweisen.',
    exampleEnglish: 'I need to transfer the rent by tomorrow.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'work'
  },
  {
    id: 'a2-w-8',
    german: 'vereinbaren',
    english: 'to agree upon / arrange (an appointment)',
    pronunciation: '[fɛɐ̯ˈʔaɪ̯nbaːʁən]',
    hint: 'Usually used with "Termin". To set slot details.',
    exampleGerman: 'Lass uns einen Termin vereinbaren.',
    exampleEnglish: 'Let us arrange an appointment.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'work'
  },
  {
    id: 'a2-w-9',
    german: 'die Verspätung',
    english: 'the delay',
    pronunciation: '[fɛɐ̯ˈʃpɛːtʊŋ]',
    hint: 'Arriving or starting later than planned.',
    exampleGerman: 'Unser Zug hatte zwanzig Minuten Verspätung.',
    exampleEnglish: 'Our train had twenty minutes delay.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'personal',
    gender: 'die',
    nounWithoutArticle: 'Verspätung'
  },
  {
    id: 'a2-w-10',
    german: 'der Arbeitgeber',
    english: 'the employer',
    pronunciation: '[ˈaʁbaɪ̯tˌɡeːbɐ]',
    hint: 'The person, firm, or company that hires workers.',
    exampleGerman: 'Mein neuer Arbeitgeber ist ein großes IT-Unternehmen.',
    exampleEnglish: 'My new employer is a large IT company.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'work',
    gender: 'der',
    nounWithoutArticle: 'Arbeitgeber'
  },
  {
    id: 'a2-w-11',
    german: 'die Geschwister',
    english: 'the siblings',
    pronunciation: '[ɡəˈʃvɪstɐ]',
    hint: 'Brothers and sisters altogether.',
    exampleGerman: 'Ich habe zwei Geschwister: einen Bruder und eine Schwester.',
    exampleEnglish: 'I have two siblings: a brother and a sister.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'family',
    gender: 'die',
    nounWithoutArticle: 'Geschwister'
  },
  {
    id: 'a2-w-12',
    german: 'die Ausbildung',
    english: 'the apprenticeship / education path',
    pronunciation: '[ˈaʊ̯sbɪldʊŋ]',
    hint: 'A structured dual vocation-education practice in Germany.',
    exampleGerman: 'Sie macht eine Ausbildung zur Krankenschwester.',
    exampleEnglish: 'She is doing an apprenticeship to become a nurse.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'education',
    gender: 'die',
    nounWithoutArticle: 'Ausbildung'
  },
  {
    id: 'a2-w-13',
    german: 'das Gehalt',
    english: 'the salary',
    pronunciation: '[ɡəˈhalt]',
    hint: 'Regular monthly payment for work.',
    exampleGerman: 'Sein Gehalt wird am Monatsende gezahlt.',
    exampleEnglish: 'His salary is paid at the end of the day.',
    type: 'word',
    level: ProficiencyLevel.A2,
    category: 'work',
    gender: 'das',
    nounWithoutArticle: 'Gehalt'
  },

  // A2 SENTENCES
  {
    id: 'a2-s-1',
    german: 'Ich möchte einen Termin beim Arzt vereinbaren.',
    english: 'I would like to make an appointment with the doctor.',
    pronunciation: '[ɪç ˈmœçtə ˈaɪ̯nən tɛʁˈmiːn baɪ̯m aːɐ̯tst fɛɐ̯ˈʔaɪ̯nbaːʁen]',
    hint: 'Standard phrase for contacting medical clinics in Germany.',
    exampleGerman: 'Hallo, ich möchte einen Termin beim Arzt vereinbaren, weil ich Fieber habe.',
    exampleEnglish: 'Hello, I would like to make an appointment with the doctor because I have a fever.',
    type: 'sentence',
    level: ProficiencyLevel.A2,
    category: 'personal'
  },
  {
    id: 'a2-s-2',
    german: 'Wegen des schlechten Wetters hat der Zug Verspätung.',
    english: 'Because of the bad weather, the train is delayed.',
    pronunciation: '[ˈveːɡn̩ dɛs ˈʃlɛçtn̩ ˈvɛtɐs hat deːɐ̯ tsuːk fɛɐ̯ˈʃpɛːtʊŋ]',
    hint: 'Uses the genitive case "wegen des schlechten Wetters".',
    exampleGerman: 'Es schneit stark. Wegen des schlechten Wetters hat der Zug Verspätung.',
    exampleEnglish: 'It is snowing heavily. Because of the bad weather, the train is delayed.',
    type: 'sentence',
    level: ProficiencyLevel.A2,
    category: 'personal'
  },
  {
    id: 'a2-s-3',
    german: 'Könnten Sie mir bitte ein gutes Restaurant empfehlen?',
    english: 'Could you please recommend a good restaurant to me?',
    pronunciation: '[ˈkœntn̩ ziː miːɐ̯ ˈbɪtə aɪ̯n ˈɡuːtəs ʁɛstoˈʁã ɛmˈpfeːlən]',
    hint: 'Polite inquiry using Konjunktiv II.',
    exampleGerman: 'Guten Abend! Könnten Sie mir bitte ein gutes Restaurant empfehlen, das deutsche Küche hat?',
    exampleEnglish: 'Good evening! Could you please recommend a good restaurant to me that serves German cuisine?',
    type: 'sentence',
    level: ProficiencyLevel.A2,
    category: 'shopping'
  },
  {
    id: 'a2-s-4',
    german: 'Ich habe mich um eine neue Arbeitsstelle beworben.',
    english: 'I have applied for a new job.',
    pronunciation: '[ɪç ˈhaːbə mɪç ʊm ˈaɪ̯nə ˈnɔY̯ə ˈaʁbaɪ̯tsˌʃtɛlə bəˈvɔʁbn̩]',
    hint: 'Uses reflexive "sich bewerben um" in perfect tense.',
    exampleGerman: 'Ich war unzufrieden, deshalb habe mich um eine neue Arbeitsstelle beworben.',
    exampleEnglish: 'I was dissatisfied, therefore I have applied for a new job.',
    type: 'sentence',
    level: ProficiencyLevel.A2,
    category: 'work'
  },
  {
    id: 'a2-s-5',
    german: 'Es tut mir leid, aber ich muss unseren Termin absagen.',
    english: 'I am sorry, but I have to cancel our appointment.',
    pronunciation: '[ɛs tuːt miːɐ̯ laɪ̯t ˈaːbɐ ɪç mʊs ˈʊnzəʁən tɛʁˈmiːn ˈapˌzaːɡn̩]',
    hint: 'Used to politely cancel a pre-arranged plan.',
    exampleGerman: 'Es tut mir leid, aber ich muss unseren Termin absagen, da ich arbeiten muss.',
    exampleEnglish: 'I am sorry, but I have to cancel our appointment, as I have to work.',
    type: 'sentence',
    level: ProficiencyLevel.A2,
    category: 'work'
  },
  {
    id: 'a2-s-6',
    german: 'Wenn ich mehr Zeit hätte, würde ich mehr reisen.',
    english: 'If I had more time, I would travel more.',
    pronunciation: '[vɛn ɪç meːɐ̯ tsaɪ̯t ˈhɛtə ˈvY̯ʁdə ɪç meːɐ̯ ˈʁaɪ̯zn̩]',
    hint: 'Hypothetical conditional sentence in Konjunktiv II.',
    exampleGerman: 'Wenn ich mehr Zeit hätte, würde ich mehr reisen, aber ich muss lernen.',
    exampleEnglish: 'If I had more time, I would travel more, but I have to study.',
    type: 'sentence',
    level: ProficiencyLevel.A2,
    category: 'personal'
  },
  {
    id: 'a2-s-7',
    german: 'Die Ausbildung ist eine wichtige Bildungsstufe.',
    english: 'The apprenticeship is an important education tier.',
    pronunciation: '[diː ˈaʊ̯sbɪldʊŋ ɪst ˈaɪ̯nə ˈvɪçtɪɡə ˈbɪldʊŋsˌʃtuːfə]',
    hint: 'Expressing the significance of vocational pathways.',
    exampleGerman: 'Die Ausbildung in Deutschland ist sehr gut strukturiert.',
    exampleEnglish: 'The apprenticeship in Germany is very well structured.',
    type: 'sentence',
    level: ProficiencyLevel.A2,
    category: 'education'
  }
];
